/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

export interface Order {
  id: string;
}

export interface OrderLine {
  id: string;
  order_id: string;
  price: number;
  product_id: string;
  quantity: number;
}

export interface DB {
  order: Order;
  order_line: OrderLine;
}
