/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Numeric = ColumnType<string, number | string, number | string>;

export interface Order {
  id: string;
}

export interface OrderLine {
  id: string;
  order_id: string;
  price: Numeric;
  product_id: string;
  quantity: number;
}

export interface DB {
  order: Order;
  order_line: OrderLine;
}
